### ISSUE TITLE
Use placeholder for emptyInputMsg and emptyOutputMsg

### ISSUE THREAD

**Issue by carlmjohnson** [mholt/json-to-go#100]
The page uses JS to put in emptyInputMsg and emptyOutputMsg, but if you paste too fast while it's loading you can end up with the empty message at the bottom of your input. In modern HTML, this is built into the browser now, so there's no need to handle this manually in JS. Just change the input tag to `<input placeholder="Paste JSON here">` and browsers will handle it all automatically.

**Comment by mholt** [comment]
Thanks, but I just tried and that doesn't seem to work for `<div>` tags.
