### ISSUE TITLE
JSON key "2.0" gets converted to "2.1" struct tag

### ISSUE THREAD

**Issue by madislohmus** [mholt/json-to-go#104]
Input `{"2.0":"asdg"}` gets converted to:
```go
type AutoGenerated struct {
	Two1 string `json:"2.1"`
}
```

**Comment by mholt** [comment]
Can't reproduce:

```
{"2.0":"asdg"}
```

yields

```
type AutoGenerated struct {
	Two0 string `json:"2.0"`
}
```

**Comment by madislohmus** [comment]
Sorry, just checked and it only happens with chrome and when I'm logged in. Doesn't happen in incognito, or using chrome as a guest or in Safari. Just to show that I'm not completely crazy:

https://user-images.githubusercontent.com/6338873/154111894-9e59c37f-70f4-4f6f-a871-e0eab479408b.mov
