### ISSUE TITLE
CSV Parsing

### ISSUE THREAD

**Issue by alexmullins** [mholt/json-to-go#11]
Matt,

Last week you recommended Papa Parse for parsing CSV data structures to Go structs.  I used your JSON-to-Go as a starting template and came up with:

https://alexmullins.github.io/csv-to-go/

Papa Parse made the task extremely simple. Just parse the CSV and set the scope to the .data JSON object representing the CSV data and that's it. Couldn't have been easier! 

 The only quirk I've found is the need to use "Shift+enter" to get the '\n' for parsing. 

I'll come up with a few sample data structures to parse and add them later.

**Comment by mholt** [comment]
Ha, cool! Glad it worked out well, looking forward to seeing the samples to play with. :+1:

**Comment by mholt** [comment]
Also, let me know when it's ready to show off and I'll tweet it 'n stuff.
