### ISSUE TITLE
I want you to publish JSON-to-Go as an npm package

### ISSUE THREAD

**Issue by nkmr-jp** [mholt/json-to-go#116]
Hello!
I have always found JSON-to-Go useful.
I have a request, please release JSON-to-Go as an npm package.

Now I am making a CLI tool to convert API's JSON payload to go struct. ([nkmr-jp/api-to-go](https://github.com/nkmr-jp/api-to-go))
I am using JSON-to-Go code to convert from json to go.

Currently, I use JSON-to-Go by cloning it with the git clone command, but I would like to install and use it as an npm package if possible.

If you release it as an npm package, many engineers will be able to develop tools using JSON-to-Go, and I think many useful tools will be created.

Please consider it!

**Comment by mholt** [comment]
I personally don't have any interest in publishing an NPM package of this. But someone else is welcome to I guess 🤷‍♂️

**Comment by nkmr-jp** [comment]
Thanks for the reply!

I searched for the package on npm but couldn't find it.
(There is a cli tool called [json-to-go-cli](https://www.npmjs.com/package/json-to-go-cli), but it has not been updated for 2 years.)

Currently, I think it's best to copy and use the latest original code.
Since you have published your code at MIT, I will copy the code and use it with credit.

Thanks for the continuous updates to JSON-to-Go!
