### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by markthethomas** [mholt/json-to-go#12]
This was and has been a HUGE timesaver. Thank you so much!

**Comment by markthethomas** [comment]
And now closing; just had to have my gratitude recorded.

**Comment by mholt** [comment]
Glad you like it! Thanks for your comment. :smile:

**Comment by ComputerFanboy** [comment]
I would also like to thank you, is there a way to donate? If not, please add one.

**Comment by mholt** [comment]
@ComputerFanboy Really informally, I guess, is this generic page I use to accept payments: https://matt.life/pay

I'm truly glad you find it helpful!
