### ISSUE TITLE
Is there a online tool converting go struct to json?

### ISSUE THREAD

**Issue by dablelv** [mholt/json-to-go#121]
I want to convert a go struct to json, but I can't find a good online tool. Why this tool don't support reverse conversion, i.e. coverting go struct to json?

**Comment by mholt** [comment]
Because you can just do `json.Marshal()` in Go. 🤷‍♂️ JSON isn't really strongly typed.

**Comment by dablelv** [comment]
> Because you can just do `json.Marshal()` in Go. 🤷‍♂️ JSON isn't really strongly typed.

Thanks reply. I also have another question. Why I cant'f find the frontend codes in your repo mholt/json-to-go?

**Comment by mholt** [comment]
It's on the gh-pages branch
