### ISSUE TITLE
Greedy time regex

### ISSUE THREAD

**Issue by ejcx** [mholt/json-to-go#122]
This bit me today, after years of using this site. Really amazing that this is the first bug I've hit.

```
let val = "my name is bob 2023-11-03T02:18:10+00:00"
if (/\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(\.\d+)?(\+\d\d:\d\d|Z)/.test(val)) {
    console.log("time.Time");
}
> time.Time
```

The code in question: https://github.com/mholt/json-to-go/blob/master/json-to-go.js#L324-L325

**Comment by mholt** [comment]
Never thought of that -- thanks for the PR. I'm surprised that's the first bug you've hit, since we have a fair number of them :sweat_smile:
