### ISSUE TITLE
JSON.parse: expected property name or '}' at line 1 column 2 of the JSON data

### ISSUE THREAD

**Issue by 3052** [mholt/json-to-go#125]
input:

~~~json
{
    "message": {
        "subject": "Meet for lunch?",
        "body": {
            "content": "The new cafeteria is open."
        },
        "toRecipients": [
            {
                "emailAddress": {
                    "address": "hello@world.com"
                }
            }
        ]
    }
}
~~~

**Comment by 3052** [comment]
ah, the problem is the "spaces" in the input are No-Break Space U+00A0. looks like that's invalid for both the JSON parser and Go parser:

panic: invalid character '\u00a0' looking for beginning of value

so maybe its my error. might be good to warn the user though if NBSP are found in the input

**Comment by mholt** [comment]
Ha, wow. I've never seen that happen before but if it happens repeatedly maybe I'll add a quick warning... (or I'd accept a PR) :+1:
