### ISSUE TITLE
IOS as commonInitialisms 

### ISSUE THREAD

**Issue by fukaraca** [mholt/json-to-go#126]
**mobile_app_ios_download_url** json tag is converted as field -**MobileAppIosDownloadURL**-. Should we add it to commonInitialisms also?
![image](https://github.com/mholt/json-to-go/assets/93548226/846f4f31-017b-4e9a-88b3-0edc4824410e)

**Comment by mholt** [comment]
I don't think we add trademarked/brand names to initialisms.

I'm not even sure if it should be iOS or IOS, it doesn't really stand for anything anyway, hence it's not an initialism IMO.
