### ISSUE TITLE
The "https://mholt.github.io/json-to-go/" show "Unexpected token"

### ISSUE THREAD

**Issue by kkdai** [mholt/json-to-go#13]
This web site help me a lot, please  help. Thanks

**Comment by mholt** [comment]
That means your JSON input is malformed. Check it with http://jsonlint.com/.

**Comment by kkdai** [comment]
Thanks, it seems my input include some special character when I copy from go http print. However http://jsonlint.com/  help a lot.

**Comment by kkdai** [comment]
I found the json input field is rich text, it might include formatter tag once I copy json from ex:  https://dev.twitter.com/rest/reference/get/followers/list

**Comment by mholt** [comment]
Oh, that's possible... paste with Cmd+Shift+V (Ctrl+Shift+V on Windows) for plaintext.
