### ISSUE TITLE
Key "fooBar" should be converted into "FooBar"

### ISSUE THREAD

**Issue by hajimehoshi** [mholt/json-to-go#14]
IMHO, it seems more natural to keep upper case characters as they are. Now "fooBar" is converted into "Foobar".

**Comment by mholt** [comment]
If the field name is unexported, the `encoding/json` package will not be able to access it.

**Comment by hajimehoshi** [comment]
I meant JSON key 'fooBar' should be converted into Go key 'FooBar' instead of 'Foobar'. I think both would be exported.

**Comment by mholt** [comment]
Oh, yes, FooBar would be exported.

I guess this makes sense, but I don't have the time right now to make that change. PRs welcome!
