### ISSUE TITLE
Publish CLI to npm?

### ISSUE THREAD

**Issue by tj** [mholt/json-to-go#17]
Would be nicer to use via CLI I think personally! Handy tool

**Comment by mholt** [comment]
That's a good idea!

In the meantime, there are some CLI tools written in Go that already do this, plus they `go fmt` the output (this doesn't). Here's one: https://github.com/ChimeraCoder/gojson

**Comment by tj** [comment]
ahh nice thanks! I thought I had seen another but I couldn't find it

**Comment by mattn** [comment]
now about to append below into the js?
```javascript
if (typeof module != 'undefined' && !module.parent) {
  var fs = require('fs')
  var fd = process.stdin.fd;
  var length = fs.fstatSync(fd).size;
  var buffer = new Buffer(length);
  var bytesRead = fs.readSync(fd, buffer, 0, length, 0);
  var input = buffer.toString('utf8', 0, bytesRead);
  console.log(jsonToGo(input));
}
```

**Comment by mholt** [comment]
If that works, sure! Pull request welcome :smile: I'm a bit busy this week.

**Comment by mattn** [comment]
It works but must not have shebang because this is loaded from script tag. :(

**Comment by mholt** [comment]
It's not on NPM but is #23 good enough for your needs?
