### ISSUE TITLE
Bug with nested arrays

### ISSUE THREAD

**Issue by yanpozka** [mholt/json-to-go#18]
I tried to answer this [question](http://stackoverflow.com/questions/39902502/unmarshall-nested-json-arrays-in-go-golang) in StackOverFlow with **json-to-go**, but I've found a bug, this json 
`[[[{"abc": "a1"}]]]` has to be converted as slice of slices:

``` go
type AutoGenerated [][][]struct {
    Abc string `json:"abc"`
}
// or
type AutoGenerated [][]interface{}
```

To be corrected Unmarshal() like [here](https://play.golang.org/p/HKrMqnxtor)

**Comment by mholt** [comment]
Thanks to @ShevaXu, I think this is now fixed. :)
