### ISSUE TITLE
Copy struct to clipboard

### ISSUE THREAD

**Issue by wayneashleyberry** [mholt/json-to-go#24]
Hey @mholt! Thank you so much for this tool, the amount of time you've saved me is astounding.

To make things even easier, would you be open to me adding a "copy to clipboard" on the output field? I think it'd be quite nice :)

**Comment by mholt** [comment]
Thanks for the suggestion! Can that be done without Flash?

**Comment by wayneashleyberry** [comment]
Yup, don't need flash @mholt :)

**Comment by wayneashleyberry** [comment]
Closing this issue - will leave the PR open
