### ISSUE TITLE
Map interface version

### ISSUE THREAD

**Issue by rodrigo-brito** [mholt/json-to-go#31]
Hello @mholt,
I construct a similar version of this tool: https://github.com/rodrigo-brito/json-to-go-map
That version converts the JSON to a `map[string]interface{}`, that can be used for simple serialization in tests or small features.

Your tool is very useful and amazing, helped me a lot, so many times. Thank you so much! :heart:
I hope that you enjoy this version.

Best regards,
Rodrigo Brito

**Comment by mholt** [comment]
Fabulous! Thanks for sharing, glad you find this one useful too. :)

Don't mind if I close this. Thanks again for letting me know about it!
