### ISSUE TITLE
values are lost in translation

### ISSUE THREAD

**Issue by ORESoftware** [mholt/json-to-go#38]
<img width="1161" alt="screenshot 2018-04-10 21 20 08" src="https://user-images.githubusercontent.com/11139560/38581503-029928e2-3d05-11e8-93fc-0e7852026b7b.png">

where do "bar" and "baz" disappear to???

**Comment by mholt** [comment]
Hi, this tool only gives you a structure -- a type definition -- not a value. :) You will have to initialize a struct with your value to put the values in it. json.Unmarshal is what you're looking for.

**Comment by ORESoftware** [comment]
yeah sorry, I am new to golang.

I thought a struct would have the value, but the interface would NOT have the value.

that would have been my guess.
