### ISSUE TITLE
Named types fails on arrays of objects

### ISSUE THREAD

**Issue by jcbwlkr** [mholt/json-to-go#50]
Hello! Thanks for this great tool. I tried out the new non-anonymous structs feature and noticed a bug so I thought to let you know.

When you have an object that has a field which is an array of objects the generator fails. For example, this input:

```json
{
  "users": [
    {
      "name": "Gopher"
    }
  ]
}
```

When used with the classic behavior it works fine. When I uncheck the box so I get two separate types I instead get this
```
2:11: expected type, found 'STRING' `json:"users"`
```

**Comment by mholt** [comment]
Oops, it's possible that I broke this by adding a `\n` somewhere, recently.
