### ISSUE TITLE
Types are no longer showing up in the final output.

### ISSUE THREAD

**Issue by josephspurrier** [mholt/json-to-go#58]
Name should have a type of "string".

![image](https://user-images.githubusercontent.com/2394539/54049627-045e1b00-41ab-11e9-8e40-1e2099f6c650.png)

**Comment by mahdi-hosseini** [comment]
Hard refresh to re-enter to get the right output.

This is what I got:
```go
type AutoGenerated struct {
	Organization struct {
		Name string `json:"name"`
	} `json:"organization"`
}
```

**Comment by josephspurrier** [comment]
Yep, that works. Thanks for the quick reply!
