### ISSUE TITLE
Go to JSON

### ISSUE THREAD

**Issue by plutov** [mholt/json-to-go#62]
I was using the site to convert JSON to Go structs, but recently I wanted to do an opposite to get a JSON string from my Go struct, and it's not yet possible.

Do you think it will make sense to have this option as well? Using left/right arrows and make interface bi-directional.

If you are happy with this idea, I can provide a PR.

**Comment by mholt** [comment]
I'm not sure what the output would be, since JSON is not strongly typed; I'd rather not get into JSON schemas or anything like that.

**Comment by horus** [comment]
> I was using the site to convert JSON to Go structs, but recently I wanted to do an opposite to get a JSON string from my Go struct, and it's not yet possible.
> 
> Do you think it will make sense to have this option as well? Using left/right arrows and make interface bi-directional.
> 
> If you are happy with this idea, I can provide a PR.

[This](http://horus.github.io/go-to-json/) may not be exactly what you want, but I think you might find it helpful. :-)
