### ISSUE TITLE
Change domain to json.to-go.online?

### ISSUE THREAD

**Issue by mengzhuo** [mholt/json-to-go#73]
Hi, Matt

I'm the author of yaml-to-go and I bought a domain "to-go.online".
I've set http://yaml.to-go.online to my project and it looks good.
Would you like to add json-to-go to http://json.to-go.online ?

Thanks.

p.s. I've set json.to-go.online cname to mholt.github.io
You can change it in Github project settings.

**Comment by mholt** [comment]
Thanks for the offer! I think I'm happy with it where it is right now though. :+1:
