### ISSUE TITLE
Proposal: optimize size and request count

### ISSUE THREAD

**Issue by YaroslavPodorvanov** [mholt/json-to-go#74]
[JSON-to-Go](https://mholt.github.io/json-to-go/) use [highlight.js](https://highlightjs.org/) and load **all** languages
[JSON-to-Proto](https://json-to-proto.github.io/) (copy-paste of JSON-to-Go) also use **highlight.js** but load **one** language

If you agree ➡️ i will rewrite with Webpack and one build file ➡️ this reduce loaded size

**Comment by mholt** [comment]
Sure, submit a PR and I'll take a look.

**Comment by YaroslavPodorvanov** [comment]
Great, this is first ready step ➡️ #75 

If you agree ➡️ i will use https://webpack.js.org/guides/lazy-loading/ to extract 700 KB of gofmt.js to lazy loading, and some clear code
