### ISSUE TITLE
Error parsing [][]string structure

### ISSUE THREAD

**Issue by theriverman** [mholt/json-to-go#76]
Hi,

The following JSON is parsed incorrectly when NOT using inline structures:
```json
{
  "assigned_to": 7,
  "tags": [
    [
      "hello",
      "#ab14d9"
    ]
  ]
}
```

When using inline structures, it's converted as expected:
```go
type AutoGenerated struct {
	AssignedTo int        `json:"assigned_to"`
	Tags       [][]string   `json:"tags"`
}
```

When NOT using inline structures, parsing fails:
```txt
3:13: expected ';', found '[' (and 1 more errors)
```
It should return something like:
```go
type Tags [][]string
type AutoGenerated struct {
	AssignedTo int        `json:"assigned_to"`
	Tags       Tags          `json:"tags"`
}
```

Thanks for the awesome tool!

**Comment by lhlyu** [comment]
@theriverman 

You can try this online [tool](https://github.com/misakafs/json-to-go)
