### ISSUE TITLE
cannot unmarshal number <very long number> into Go struct field ... of type int64

### ISSUE THREAD

**Issue by zen37** [mholt/json-to-go#79]
https://ifconfig.co/json returns "ip_decimal":20 digits number
It is translated into int64, it should have been float64 to avoid the error.

Some edits to make it clearer.

**Comment by mholt** [comment]
Why? It's an integer...

**Comment by zen37** [comment]
there was no error when changing the data type of the Go struct field from int64 to float64

**Comment by mholt** [comment]
That doesn't mean it is right? Anyway, closing... nothing to do here. You're free to change it yourself.

**Comment by zen37** [comment]
GO int64 is 19 digits.
If JSON number is > 19 digits convert to float64, if not leave it as it is now, int64.

**Comment by mholt** [comment]
The number is only 10 digits long.

**Comment by zen37** [comment]
The number retrieved in https://ifconfig.co/json is 20 digits long.

**Comment by mholt** [comment]
It's 10 for me, but I see you just edited your original post to specify 20 digits. Maybe you are using IPv6.

A 64 bit integer has more unique values than a 64 bit float.

Using floats for integer values will be wrong for most users. If you require floats, just change it in your code.
