### ISSUE TITLE
Error on parsing regExp as String 

### ISSUE THREAD

**Issue by pittidoe90** [mholt/json-to-go#88]
If you try to parse a regExp within a string it returns a error.

for example:

`{"regExp":"\d+"}`

![image](https://user-images.githubusercontent.com/75275635/109653328-3370b280-7b61-11eb-98ac-6ecf32888bc4.png)

**Comment by mholt** [comment]
Pretty sure `\d` is not a valid escape sequence; see https://jsonlint.com/. You need `\\d` for a literal backslash.
