### ISSUE TITLE
VSCode Extension ?

### ISSUE THREAD

**Issue by buildingwatsize** [mholt/json-to-go#92]
Is there any chance that this project will be a VSCode Extension?

Appreciate.

**Comment by mholt** [comment]
Anyone's welcome to do that, but I don't have the time for it.

**Comment by Maracko** [comment]
I am interested in doing an extension for json-to-go

**Comment by Maracko** [comment]
It is live at https://marketplace.visualstudio.com/items?itemName=maracko.json-to-go

Any feedback is welcome!

**Comment by mholt** [comment]
That's cool! I will have to try this out.

**Comment by buildingwatsize** [comment]
Interesting! It's actually good. 👍

**Comment by mholt** [comment]
We can probably close this, then.

Feel free to submit a PR to add a link to it on the web page!
