### ISSUE TITLE
mholt.github.io/json-to-go isn't outputting CamelCase as expected

### ISSUE THREAD

**Issue by calumj** [mholt/json-to-go#93]
The version of json-to-go hosted at mholt.github.io is currently ignoring the casing of the input JSON.

Input:

```
{"exampleJSON":"",
"anotherTest": ""}
```

Output:

```
type Autogenerated struct {
	Examplejson string `json:"exampleJSON"`
	Anothertest string `json:"anotherTest"`
}
```

Expected Output:

```
type AutoGenerated struct {
	ExampleJSON string `json:"exampleJSON"`
	AnotherTest string `json:"anotherTest"`
}
```

I have tried clearing service workers and running in incognito and the issue persists.

**Comment by hirochachacha** [comment]
I sent PR #94

**Comment by mikegleasonjr** [comment]
Same thing on the VS Code extension, just to be clear that it is not only on `mholt.github.io`...

**Comment by mholt** [comment]
Should be working now
